import sys, os, hashlib, re, binascii

def Search_in_SystemCatch(keywordInSystem):
        print("below is for system catch directory\n")
        #check system catch
        print("# grep -ril -e \'%s\' /data/local/tmp/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/local/tmp/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/tmp/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/tmp/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/system/usagestats/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/system/usagestats/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/system/appusagestats/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/system/appusagestats/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/system/dropbox/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/system/dropbox/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/tombstones/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/tombstones/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/anr/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/anr/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /dev/log/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /dev/log/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /data/local/log/ :" %(keywordInSystem))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/local/log/| grep -v Inspeckage \" ; echo echo:$?'" %(keywordInSystem)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")

def Search_in_Data(keywordInData, pgname):
        print("# grep -ril -e \'%s\' /data/data/%s :" %(keywordInData, pgname))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /data/data/%s/ | grep -v Inspeckage \" ; echo echo:$?'" %(keywordInData, pgname)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
        print("# grep -ril -e \'%s\' /sdcard/ " %(keywordInData))
        recvAll = os.popen("adb shell 'su -c \"grep -ril -e \'%s\' /sdcard/ | grep -v Inspeckage \" ; echo echo:$? '" %(keywordInData)).read()
        recvCode = re.search('(?<=echo:)\d+', recvAll)
        print("Find" if recvCode.group(0)=='0' else "Not Found")
        print("------")
if __name__=="__main__":
    packagename = sys.argv[2]
    keywordFile = open(sys.argv[1], 'r')
    #os.system("adb shell su -c 'cp /data/app/%s*/base.apk /sdcard'" %(sys.argv[1]))
    #os.system("adb pull /sdcard/base.apk")
    #os.system("adb shell rm /sdcard/base.apk")
    for keyword in keywordFile.readlines():
        print("---use plaintext to search---\n")
        Search_in_Data(keyword[:-1], packagename)
        Search_in_SystemCatch(keyword[:-1])
        print("---use hex to search---\n")
        Search_in_Data(keyword[:-1].encode("hex"), packagename)
        Search_in_SystemCatch(keyword[:-1].encode("hex"))
        print("---use base64 to search---\n")
        Search_in_Data(keyword[:-1].encode("base64").replace('\n', ''), packagename)
        Search_in_SystemCatch(keyword[:-1].encode("base64").replace('\n', ''))
        print("---use md5 to search---\n")
        Search_in_Data(hashlib.md5(keyword[:-1]).hexdigest(), packagename)
        Search_in_SystemCatch(hashlib.md5(keyword[:-1]).hexdigest())
        print("---use sha1 to search---\n")
        Search_in_Data(hashlib.sha1(keyword[:-1]).hexdigest(), packagename)
        Search_in_SystemCatch(hashlib.sha1(keyword[:-1]).hexdigest())
        print("---use utf-8 to search---\n")
        Search_in_Data(repr(keyword[:-1]).replace("'",""), packagename)
        Search_in_SystemCatch(repr(keyword[:-1]).replace("'",""))
        print("---use binary to search---\n")
        Search_in_Data((' '.join(format(ord(x), 'b')for x in keyword[:-1])), packagename)
        Search_in_SystemCatch((' '.join(format(ord(x), 'b')for x in keyword[:-1])))
        
